### ISSUE TITLE
Is this just a capture macro??

### ISSUE THREAD

**Issue by yeappidw** [k4sud0n/ebook-to-PDF#1]
I was finding decryption tool for yes24, and I found your repository.
There is no description of your program.
Is this just a capture program??

**Comment by k4sud0n** [comment]
This is a program that automatically captures the pages and converts into pdf.
I'm not pretty sure you can decrypt YES24.

My program is incomplete yet..so if you are interested in getting pdf from yes24, 
maybe you can follow [this link](https://github.com/eastshine12/eBookToPdf) and check it out.
